
import { Inter } from "next/font/google";
import "./globals.css";
import Context from "@/app/libs/context";
import Header from "@/app/header";
import Head from "next/head";
import {Fragment} from "react";
import Footer from "@/app/footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {

    return (
        <html>
        <Head>
            <html lang="en" className="bg-lands-bg"  />
        </Head>
        <body>
        <Fragment>

            <Header/>
            <Context children={children}/>
            <Footer/>
        </Fragment>
        </body>
        </html>
    );
}
